<MyLayout>
    BoxLayout:
        orientation: 'vertical'

        MDToolbar:
            title: 'Dashboard'

        BoxLayout:
            MDBoxLayout:
                orientation: 'vertical'
                spacing: dp(10)
                padding: dp(20)

                MDRaisedButton:
                    text: 'Button 1'

                MDRaisedButton:
                    text: 'Button 2'

                MDRaisedButton:
                    text: 'Button 3'

            MDBoxLayout:
                orientation: 'vertical'
                spacing: dp(10)
                padding: dp(20)

                MDRaisedButton:
                    text: 'Button 4'

                MDRaisedButton:
                    text: 'Button 5'

                MDRaisedButton:
                    text: 'Button 6'
